services:
  - type: web
    name: staffroom
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn web_app:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
  - type: pserv
    name: staffroom-db
    env: postgresql
